name: bats

on: 
  workflow_call:
    inputs:
      dependencies:
        required: false
        type: string
        default: ""
      test-glob:
        required: true
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Fish and dependencies
        run: |
          sudo apt update
          sudo apt install -y bats bats-assert bats-file bats-support
          sudo apt install -y ${{ inputs.dependencies }}

      - name: Run bats
        run: bats ${{ inputs.test-glob }}
