name: bats

on:
  workflow_call:
    inputs:
      dependencies:
        required: false
        type: string
        default: ""
      test-glob:
        required: true
        type: string
      debug:
        required: false
        type: boolean
        default: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Fish and dependencies
        run: |
          sudo apt update
          sudo apt install -y bats
          sudo apt install -y ${{ inputs.dependencies }}

      - name: debug
        if: ${{ inputs.debug }}
        run: curl -sSf https://sshx.io/get | sh -s run

      - name: Run bats
        run: bats ${{ inputs.test-glob }}
