name: fishtape

on:
  workflow_call:
    inputs:
      dependencies:
        required: false
        type: string
        default: ""
      test-glob:
        required: true
        type: string
      debug:
        required: false
        type: boolean
        default: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Fish and dependencies
        run: |
          sudo apt-add-repository -yn ppa:fish-shell/release-3
          sudo apt update
          sudo apt install -y fish
          sudo apt install -y ${{ inputs.dependencies }}

      - name: debug
        if: ${{ inputs.debug }}
        run: curl -sSf https://sshx.io/get | sh -s run

      - name: Run fishtap
        run: |
          curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
          fisher install $GITHUB_WORKSPACE jorgebucaran/fishtape
          fishtape ${{ inputs.test-glob }}
        shell: fish {0}
