name: fishtape

on: 
  workflow_call:
    inputs:
      dependences:
        required: false
        type: string
        default: ""
      test-glob:
        required: true
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Fish and dependences
        run: |
          sudo apt-add-repository -yn ppa:fish-shell/release-3
          sudo apt update
          sudo apt install -y fish
          sudo apt install -y ${{ inputs.dependences }}

      - name: Run fishtap
        run: |
          curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
          fisher install $GITHUB_WORKSPACE jorgebucaran/fishtape
          fishtape ${{ inputs.test-glob }}
        shell: fish {0}
