name: release-obsidian-plugin

on:
  workflow_call:

permissions:
  contents: write
  packages: write

jobs:
  version:
    name: Get the version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Get the version
        id: tag
        run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
      - name: Echo tag
        run: echo ${{ steps.tag.outputs.version }}

  release:
    runs-on: ubuntu-latest
    needs: version
    env:
      VERSION: ${{ needs.version.outputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build plugin
        run: npm run build

      - name: Create release
        run: |
          GIT_TAG_TITLE=$(git tag -l --format='%(contents:subject)' ${{env.VERSION}} 2>/dev/null)
          GIT_TAG_NOTE=$(git tag -l --format='%(contents:body)' ${{env.VERSION}} 2>/dev/null)
          echo "GIT_TAG_TITLE=$GIT_TAG_TITLE"
          echo "GIT_TAG_NOTE=$GIT_TAG_NOTE"
          if [ -f styles.css ]; then
            gh release create "${{env.VERSION}}" --verify-tag -t "$GIT_TAG_TITLE" -n "$GIT_TAG_NOTE" main.js manifest.json styles.css
          else
            gh release create "${{env.VERSION}}" --verify-tag -t "$GIT_TAG_TITLE" -n "$GIT_TAG_NOTE" main.js manifest.json
          fi
        env:
          GH_TOKEN: ${{ github.token }}
