name: sync-fork

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

on:
  workflow_call:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo sync $REPOSITORY -b $BRANCH_NAME
        env:
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
